language: php
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      secure: A7sah8A/H3KvtgMYB9tgI/gih8Ukb7t5UaXqKXTE3MN5J1/JadeqyKLuSR3v/iPiJ0aOJu/TCxYPhTmBXOIKU8NgWUITbFvOc0MH6ejuUVRa6VNMRmibE4JM5IOyNXYl1NhIBu+h8c+WSZ+gawuIDd4li1B+5I6cCXX704TrfkxKKkQAajDO2glUIqjHI2y+2NKCzHQp6UkD8WThe4LxXYt2xfDRH9dldyEO7biVxUFQKTcn8HP82X6rrkAUP9yPt2R+5OwJEBUBlvKtYzHbh6TEG7TGmcOJKoi8QGY3Nc9TSgJ754gjNgu3dhbVjFQDRP0nZcdd0N4fcRN4BxaG3jZyLcDt7xOm/7ONGgNog5c977BwsNCUmXBhypGqXiHh1scfM8Sot3lEtc+kP9pkdVT1PlgPRxzFMzhaCaUZcJL19zEORx6D4Hdkd8iMOydZQdcBbelzSTXIvPSrdc95lDIU3wVEe2hJUiqUiB8m+/8Llhk/7NPJF3hLyIISBaLyGNNj1aStU2j6x/ENzFNZAXGizt8MhKXJ7RvnmYYzMToppQaD19pI7DygZ8kowHeI2n19NBifnRFqb9/yaOy3Wags6y3s+XW1IFx9rU5YAk5xwPfat/JsLi1/54wTNnrjLx5PwyYI0GPco/6lOKFwEF5Dtjv+6Hy+OXIR9KKQxQk=

php:
- 5.5
- 5.6
- 7
- nightly

env:
- WP_VERSION=latest WP_MULTISITE=0

matrix:
  allow_failures:
    - php: nightly

install:
  - echo $TRAVIS_OS_NAME
  - export PATH=./node_modules/.bin/:$PATH
  - rm -rf ~/.nvm && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 6.0.0
  - nvm use 6
  - npm cache clean
  - npm install -g gulp
  - npm install --loglevel error
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install

script:
  - npm run build
